### PR TITLE
Fixed the gopath for github

### PR DESCRIPTION
**Pull request by mustafaakin**
Since you said it is moved on the github, I wanted to fix the paths for downloading and importing the package

### CODE REVIEW

**Comment by mustafaakin** [comment]
Sorry, wrong import path!

**Comment by kshlm** [comment]
@mustafaakin Thanks for noticing this. You nearly had the import path correct. It should be `github.com/kshlm/gogfapi/gfapi`. If you fix that, I'd merge this.

**Comment by mustafaakin** [comment]
Fixed it now.

**Comment by kshlm** [comment]
Thanks @mustafaakin

**Pull request merged**
